### ISSUE TITLE
Any chance this could be updated to bluej 5.1.0

### ISSUE THREAD

**Issue by Ph-ill** [DavidoTek/bluej-snap#1]
thank you :)

**Comment by DavidoTek** [comment]
Will be a bit fiddly as it uses a new JavaFX version not included in the repos, but definitively possible.

ToDo
- [X] OpenJDK 17 [1](https://github.com/DavidoTek/bluej-snap/blob/18c504c2b20e318e542220ebdc31869b5982ad3b/snap/snapcraft.yaml#L32) [2](https://github.com/DavidoTek/bluej-snap/blob/18c504c2b20e318e542220ebdc31869b5982ad3b/snap/snapcraft.yaml#L37)
- [X] JavaFX 16 [1](https://github.com/DavidoTek/bluej-snap/blob/18c504c2b20e318e542220ebdc31869b5982ad3b/snap/snapcraft.yaml#L33) [2](https://github.com/jgneff/openjfx/blob/122a3031b3bb1b6703b12926fd368869e1083b63/snap/snapcraft.yaml#L80)
- [X] [BlueJ 5.1.0](https://bluej.org/versions.html) [1](https://github.com/DavidoTek/bluej-snap/blob/18c504c2b20e318e542220ebdc31869b5982ad3b/snap/snapcraft.yaml#L2) [2](https://github.com/DavidoTek/bluej-snap/blob/18c504c2b20e318e542220ebdc31869b5982ad3b/snap/snapcraft.yaml#L29)

**Comment by DavidoTek** [comment]
BlueJ 5.1.0 is available on the `beta` channel. Will release on `stable` soon.

You can test it by:
- Installing it using `snap install --beta bluej`
- Updating to edge channel using `snap refresh --beta bluej`
